In [ ]:
import numpy as np
import heapq as hq
from typing import Union

In [ ]:
class Graph:

    def __init__(self, adjacency_mat: Union[np.ndarray, str]):
        """

        Unlike the BFS assignment, this Graph class takes an adjacency matrix as input. `adjacency_mat`
        can either be a 2D numpy array of floats or a path to a CSV file containing a 2D numpy array of floats.

        In this project, we will assume `adjacency_mat` corresponds to the adjacency matrix of an undirected graph.

        """
        if type(adjacency_mat) == str:
            self.adj_mat = self._load_adjacency_matrix_from_csv(adjacency_mat)
        elif type(adjacency_mat) == np.ndarray:
            self.adj_mat = adjacency_mat
        else:
            raise TypeError('Input must be a valid path or an adjacency matrix')
        self.mst = None

    def _load_adjacency_matrix_from_csv(self, path: str) -> np.ndarray:
        with open(path) as f:
            return np.loadtxt(f, delimiter=',')

In [ ]:
#prim = Graph('/Users/giovanniaviles/Documents/Winter_2023/BMI_203/hw4-prim-mst/data/small.csv')

In [148]:
prim = np.loadtxt('/Users/giovanniaviles/Documents/Winter_2023/BMI_203/hw4-prim-mst/data/small.csv', delimiter=',')
print(prim)

[[0. 5. 0. 5.]
 [5. 0. 1. 2.]
 [0. 1. 0. 4.]
 [5. 2. 4. 0.]]


In [165]:
i = np.where(prim[1]==np.min(prim[1][np.nonzero(prim[1])]))
j = np.where(prim[0] == np.min(prim[0]))
m = min(i for i in prim[0] if i > 0)
prim[0][m]
print(m)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [197]:
minimum_edge_values_in_array = np.where(prim>0, prim, np.inf).min(axis=1)
print(minimum_edge_values_in_array)  # Not helpful because edge selection dependent on current node

[5. 1. 1. 2.]


In [261]:
nonzero_indices = np.nonzero(prim[1])
nonzero_indices = np.array(m).flatten()


[0 2 3]


In [271]:
nonzero_indices_two = [i for i, x in enumerate(prim[1]) if x > 0]
print(nonzero_indices_two)

[0, 2, 3]


In [282]:
m = min([x for x in prim[1] if x > 0])
min_index, = np.where(prim[1] == m)
print(min_index)

[5]


In [ ]:
heap = []
hq.heapify(heap)
item = [20, 4, 8, 10, 5, 7, 6, 2, 9]
for i in item:
    hq.heappush(heap, i)
heap.sort()

In [110]:
np.ndenumerate(prim_read_in)

TypeError: 'ndenumerate' object is not subscriptable

In [136]:
vertices = []
for i in prim_read_in.tolist():
    hq.heappush(vertices, i)
print(vertices)
hq.nsmallest(1, vertices)
#for i, j in enumerate(prim_read_in.tolist()):
#    hq.heappush(vertices, j)  # Make heap of vertices
#print(vertices)

[[0.0, 1.0, 0.0, 4.0], [5.0, 0.0, 1.0, 2.0], [0.0, 5.0, 0.0, 5.0], [5.0, 2.0, 4.0, 0.0]]


[[0.0, 1.0, 0.0, 4.0]]

In [98]:
start = prim_read_in[0][0]
prim.mst.add(start)
for a in prim_read_in[start]:
    hq.heappush(vertices, a)
while prim.mst:
    weight, next_node = hq.heappop()
for i, j in enumerate(prim_read_in.tolist()):
    hq.heappush(vertices, i)

print(vertices)

[0, 1, 2, 3]


In [ ]:
prim.mst = []  # Initialize mst as a priority queue
hq.heapify(prim.mst)

outgoing_edges = []  # Initialize outgoing_edges as a priority queue
hq.heapify(outgoing_edges)

In [95]:
visited = set()  # Initialize a set to keep track of visited nodes
weights = []
for i, j in enumerate(prim_read_in.tolist()):

    visited.add(i)  # Add vertex to visited



for i, j in enumerate(prim_read_in.tolist()):
    visited.add(i)  # Add vertex to visited
    for edges in prim_read_in.tolist()[i]:  # Access adjacency matrix values
        hq.heappush(outgoing_edges, edges)  # Push all edge weights from one node to heap
        outgoing_edges.sort()  # Sort edges by weight
        weights.add(hq.heappop(outgoing_edges))  # Add smallest weight of neighboring edges


    hq.heappush(prim.mst, prim_read_in[i])  # Add
    weights.add(hq.heappop(outgoing_edges))  # Add smallest weight of neighboring edges

# Need a while group to add nodes to visited

outgoing_edges = []  # Initialize outgoing_edges as a priority queue
hq.heapify(outgoing_edges)

0.0
5.0
0.0
5.0
5.0
0.0
1.0
2.0
0.0
1.0
0.0
4.0
5.0
2.0
4.0
0.0


In [ ]:
# Add initial vertex
visited

In [ ]:
while v not in visited:
    # Pop lowest weight edge from priority queue
    hq.heappop(outgoing_edges)

    if next_v not in visited:
        hq.heappush(self.mst, next_v)  # Add edge to mst
        visited.add(next_v)

In [ ]:
total = 0                   # Total cost of edges in tree
explored = set()            # Set of vertices in tree
start = next(iter(graph))   # Arbitrary starting vertex
unexplored = [(0, start)]   # Unexplored edges ordered by cost
while unexplored:
    cost, winner = heappop(unexplored)
    if winner not in explored:
        explored.add(winner)
        total += cost
        for neighbour, cost in graph[winner]:
            if neighbour not in explored:
                heappush(unexplored, (cost, neighbour))
return total

In [204]:
from mst import Graph

In [205]:
prim_graph = Graph('./data/small.csv')


In [206]:
print(prim_graph)

In [210]:
len(prim_graph.adj_mat)

4

In [211]:
prim_graph.adj_mat[0]

array([0., 5., 0., 5.])

In [289]:
visited = set()

for i, j in enumerate(prim_graph.adj_mat):
    visited.add(i)
    print(j)
    heap = [_ for _ in j]
print(heap)

[0. 5. 0. 5.]
[5. 0. 1. 2.]
[0. 1. 0. 4.]
[5. 2. 4. 0.]
[5.0, 2.0, 4.0, 0.0]


In [285]:
heap = [_ for _ in prim_graph.adj_mat[random_starting_index]]

IndexError: arrays used as indices must be of integer (or boolean) type

In [388]:
# Generate a random starting index in order to randomly choose a node from which to build the mst
random_starting_index = np.random.randint(0, len(prim_graph.adj_mat))

visited = set()  # Initialize set of visited nodes
visited.add(random_starting_index)  # Add starting nodes

# Starting node's smallest edge
next_edge = min([x for x in prim_graph.adj_mat[random_starting_index] if x > 0])

# Add edge to mst
#self.mst.append(next_edge)

# Next node in mst (finds index for which distance is least)
next_node, = np.where(prim_graph.adj_mat[random_starting_index] == next_edge)
print(next_node) '''NEED TO CONTROL FOR SAME VALUES'''
# Add node to visited set
visited.add(next_node)

SyntaxError: invalid syntax (265640061.py, line 15)

In [441]:
random_starting_index = np.random.randint(0, len(prim_graph.adj_mat))
heap = [_ for _ in prim_graph.adj_mat[random_starting_index]]
heap = hq.heappush(heap)
print(heap)

TypeError: heappush expected 2 arguments, got 1

In [438]:
heap = [i if i != 0 else np.inf for i in heap]  # Replace all zeros with infinity values
heap.sort()
print(heap)

[5.0, 5.0, inf, inf]


In [439]:
hq.heappop(heap)
print(heap)

[5.0, inf, inf]


In [446]:
prim_graph.adj_mat[prim_graph.adj_mat == 0] = np.inf
print(prim_graph.adj_mat)

[[inf  5. inf  5.]
 [ 5. inf  1.  2.]
 [inf  1. inf  4.]
 [ 5.  2.  4. inf]]


In [447]:
heap = [_ for _ in prim_graph.adj_mat[random_starting_index]]
hq.heapify(heap)

In [448]:
print(heap)

[2.0, 5.0, 4.0, inf]


In [449]:
hq.heappop(heap)
print(heap)

[4.0, 5.0, inf]


In [486]:
prim_mst = []
visited = set()

random_starting_node = np.random.randint(0, len(prim_graph.adj_mat))
prim_graph.adj_mat[prim_graph.adj_mat == 0] = np.inf  # Replace all zeros with infinity
heap = [_ for _ in prim_graph.adj_mat[random_starting_node]]  # Return edges for random node
hq.heapify(heap)  # Heapify heap

visited.add(random_starting_node)  # Add first node to visited

curr_node = random_starting_node

while heap and len(visited) != len(prim_graph.adj_mat):
    shortest_edge = hq.heappop(heap)  # Pop shortest_edge
    curr_node = prim_graph.adj_mat[curr_node].tolist().index(shortest_edge)  # Assign index to next node
    if curr_node not in visited:  # Check if neighboring node is already in visited
        visited.add(curr_node)
        prim_mst.append(shortest_edge)  # Add edge to mst
        neighbor_edges = [_ for _ in prim_graph.adj_mat[curr_node]]
        hq.heappush(heap, neighbor_edges)

AttributeError: 'Graph' object has no attribute 'adj_in'

In [492]:
prim_graph.adj_mat[0]

array([inf,  5., inf,  5.])

In [495]:
val = 5.
index = prim_graph.adj_mat[0].tolist().index(val)
print(index)

1


In [430]:
heap_practice = [0.0, 1.0, 0.0, 4.0]
hq.heapify(heap_practice)
print(heap_practice)

[0.0, 1.0, 0.0, 4.0]


In [431]:
heap_practice[heap_practice == 0] = np.inf

In [432]:
print(heap_practice)

[inf, 1.0, 0.0, 4.0]


In [433]:
heap_practice = [i if i != 0 else np.inf for i in heap_practice]

In [434]:
print(heap_practice)

[inf, 1.0, inf, 4.0]


In [435]:
heap_practice.sort()
hq.heappop(heap_practice)
print(heap_practice)

[4.0, inf, inf]


In [463]:
prim_graph.adj_mat

array([[inf,  5., inf,  5.],
       [ 5., inf,  1.,  2.],
       [inf,  1., inf,  4.],
       [ 5.,  2.,  4., inf]])

In [485]:
prim_graph_index_mat = np.ndenumerate(prim_graph.adj_mat)
for i, j in enumerate(prim_graph.adj_mat):

    print(i,j[0])

0 inf
1 5.0
2 inf
3 5.0


In [464]:
random_starting_index = np.random.randint(0, len(prim_graph.adj_mat))
prim_graph.adj_mat[prim_graph.adj_mat == 0] = np.inf  # Replace all zeros with infinity
heap = [_ for _ in prim_graph.adj_mat[random_starting_index]]  # Return edges for random node

hq.heapify(heap)

In [465]:
print(heap)

[inf, 1.0, inf, 4.0]


In [467]:
shortest_edge = hq.heappop(heap)

In [468]:
print(shortest_edge)

1.0


In [ ]:
prim_graph.adj_mat[]