In [ ]:
import numpy as np
import heapq as hq
from typing import Union

In [ ]:
class Graph:

    def __init__(self, adjacency_mat: Union[np.ndarray, str]):
        """

        Unlike the BFS assignment, this Graph class takes an adjacency matrix as input. `adjacency_mat`
        can either be a 2D numpy array of floats or a path to a CSV file containing a 2D numpy array of floats.

        In this project, we will assume `adjacency_mat` corresponds to the adjacency matrix of an undirected graph.

        """
        if type(adjacency_mat) == str:
            self.adj_mat = self._load_adjacency_matrix_from_csv(adjacency_mat)
        elif type(adjacency_mat) == np.ndarray:
            self.adj_mat = adjacency_mat
        else:
            raise TypeError('Input must be a valid path or an adjacency matrix')
        self.mst = None

    def _load_adjacency_matrix_from_csv(self, path: str) -> np.ndarray:
        with open(path) as f:
            return np.loadtxt(f, delimiter=',')

In [ ]:
#prim = Graph('/Users/giovanniaviles/Documents/Winter_2023/BMI_203/hw4-prim-mst/data/small.csv')

In [148]:
prim = np.loadtxt('/Users/giovanniaviles/Documents/Winter_2023/BMI_203/hw4-prim-mst/data/small.csv', delimiter=',')
print(prim)

[[0. 5. 0. 5.]
 [5. 0. 1. 2.]
 [0. 1. 0. 4.]
 [5. 2. 4. 0.]]


In [165]:
i = np.where(prim[1]==np.min(prim[1][np.nonzero(prim[1])]))
j = np.where(prim[0] == np.min(prim[0]))
m = min(i for i in prim[0] if i > 0)
prim[0][m]
print(m)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [197]:
minimum_edge_values_in_array = np.where(prim>0, prim, np.inf).min(axis=1)
print(minimum_edge_values_in_array)  # Not helpful because edge selection dependent on current node

[5. 1. 1. 2.]


In [261]:
nonzero_indices = np.nonzero(prim[1])
nonzero_indices = np.array(m).flatten()


[0 2 3]


In [271]:
nonzero_indices_two = [i for i, x in enumerate(prim[1]) if x > 0]
print(nonzero_indices_two)

[0, 2, 3]


In [280]:
m = min([x for x in prim[1] if x > 0])
min_index, = np.where(prim[1] == m)
print(min_index)

[2]


In [ ]:
heap = []
hq.heapify(heap)
item = [20, 4, 8, 10, 5, 7, 6, 2, 9]
for i in item:
    hq.heappush(heap, i)
heap.sort()

In [110]:
np.ndenumerate(prim_read_in)

TypeError: 'ndenumerate' object is not subscriptable

In [136]:
vertices = []
for i in prim_read_in.tolist():
    hq.heappush(vertices, i)
print(vertices)
hq.nsmallest(1, vertices)
#for i, j in enumerate(prim_read_in.tolist()):
#    hq.heappush(vertices, j)  # Make heap of vertices
#print(vertices)

[[0.0, 1.0, 0.0, 4.0], [5.0, 0.0, 1.0, 2.0], [0.0, 5.0, 0.0, 5.0], [5.0, 2.0, 4.0, 0.0]]


[[0.0, 1.0, 0.0, 4.0]]

In [98]:
start = prim_read_in[0][0]
prim.mst.add(start)
for a in prim_read_in[start]:
    hq.heappush(vertices, a)
while prim.mst:
    weight, next_node = hq.heappop()
for i, j in enumerate(prim_read_in.tolist()):
    hq.heappush(vertices, i)

print(vertices)

[0, 1, 2, 3]


In [ ]:
prim.mst = []  # Initialize mst as a priority queue
hq.heapify(prim.mst)

outgoing_edges = []  # Initialize outgoing_edges as a priority queue
hq.heapify(outgoing_edges)

In [95]:
visited = set()  # Initialize a set to keep track of visited nodes
weights = []
for i, j in enumerate(prim_read_in.tolist()):

    visited.add(i)  # Add vertex to visited



for i, j in enumerate(prim_read_in.tolist()):
    visited.add(i)  # Add vertex to visited
    for edges in prim_read_in.tolist()[i]:  # Access adjacency matrix values
        hq.heappush(outgoing_edges, edges)  # Push all edge weights from one node to heap
        outgoing_edges.sort()  # Sort edges by weight
        weights.add(hq.heappop(outgoing_edges))  # Add smallest weight of neighboring edges


    hq.heappush(prim.mst, prim_read_in[i])  # Add
    weights.add(hq.heappop(outgoing_edges))  # Add smallest weight of neighboring edges

# Need a while group to add nodes to visited

outgoing_edges = []  # Initialize outgoing_edges as a priority queue
hq.heapify(outgoing_edges)

0.0
5.0
0.0
5.0
5.0
0.0
1.0
2.0
0.0
1.0
0.0
4.0
5.0
2.0
4.0
0.0


In [ ]:
# Add initial vertex
visited

In [ ]:
while v not in visited:
    # Pop lowest weight edge from priority queue
    hq.heappop(outgoing_edges)

    if next_v not in visited:
        hq.heappush(self.mst, next_v)  # Add edge to mst
        visited.add(next_v)

In [ ]:
total = 0                   # Total cost of edges in tree
explored = set()            # Set of vertices in tree
start = next(iter(graph))   # Arbitrary starting vertex
unexplored = [(0, start)]   # Unexplored edges ordered by cost
while unexplored:
    cost, winner = heappop(unexplored)
    if winner not in explored:
        explored.add(winner)
        total += cost
        for neighbour, cost in graph[winner]:
            if neighbour not in explored:
                heappush(unexplored, (cost, neighbour))
return total

In [204]:
from mst import Graph

In [205]:
prim_graph = Graph('./data/small.csv')


In [206]:
print(prim_graph)

In [210]:
len(prim_graph.adj_mat)

4

In [211]:
prim_graph.adj_mat[0]

array([0., 5., 0., 5.])