In [508]:
import numpy as np
import heapq as hq
from typing import Union

In [509]:
class Graph:

    def __init__(self, adjacency_mat: Union[np.ndarray, str]):
        """

        Unlike the BFS assignment, this Graph class takes an adjacency matrix as input. `adjacency_mat`
        can either be a 2D numpy array of floats or a path to a CSV file containing a 2D numpy array of floats.

        In this project, we will assume `adjacency_mat` corresponds to the adjacency matrix of an undirected graph.

        """
        if type(adjacency_mat) == str:
            self.adj_mat = self._load_adjacency_matrix_from_csv(adjacency_mat)
        elif type(adjacency_mat) == np.ndarray:
            self.adj_mat = adjacency_mat
        else:
            raise TypeError('Input must be a valid path or an adjacency matrix')
        self.mst = None

    def _load_adjacency_matrix_from_csv(self, path: str) -> np.ndarray:
        with open(path) as f:
            return np.loadtxt(f, delimiter=',')

In [510]:
#prim = Graph('/Users/giovanniaviles/Documents/Winter_2023/BMI_203/hw4-prim-mst/data/small.csv')

In [511]:
prim = np.loadtxt('/Users/giovanniaviles/Documents/Winter_2023/BMI_203/hw4-prim-mst/data/small.csv', delimiter=',')
print(prim)

[[0. 5. 0. 5.]
 [5. 0. 1. 2.]
 [0. 1. 0. 4.]
 [5. 2. 4. 0.]]


In [512]:
i = np.where(prim[1]==np.min(prim[1][np.nonzero(prim[1])]))
j = np.where(prim[0] == np.min(prim[0]))
m = min(i for i in prim[0] if i > 0)
prim[0][m]
print(m)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
minimum_edge_values_in_array = np.where(prim>0, prim, np.inf).min(axis=1)
print(minimum_edge_values_in_array)  # Not helpful because edge selection dependent on current node

In [ ]:
nonzero_indices = np.nonzero(prim[1])
nonzero_indices = np.array(m).flatten()


In [ ]:
nonzero_indices_two = [i for i, x in enumerate(prim[1]) if x > 0]
print(nonzero_indices_two)

In [ ]:
m = min([x for x in prim[1] if x > 0])
min_index, = np.where(prim[1] == m)
print(min_index)

In [ ]:
heap = []
hq.heapify(heap)
item = [20, 4, 8, 10, 5, 7, 6, 2, 9]
for i in item:
    hq.heappush(heap, i)
heap.sort()

In [ ]:
np.ndenumerate(prim_read_in)

In [ ]:
vertices = []
for i in prim_read_in.tolist():
    hq.heappush(vertices, i)
print(vertices)
hq.nsmallest(1, vertices)
#for i, j in enumerate(prim_read_in.tolist()):
#    hq.heappush(vertices, j)  # Make heap of vertices
#print(vertices)

In [ ]:
start = prim_read_in[0][0]
prim.mst.add(start)
for a in prim_read_in[start]:
    hq.heappush(vertices, a)
while prim.mst:
    weight, next_node = hq.heappop()
for i, j in enumerate(prim_read_in.tolist()):
    hq.heappush(vertices, i)

print(vertices)

In [ ]:
prim.mst = []  # Initialize mst as a priority queue
hq.heapify(prim.mst)

outgoing_edges = []  # Initialize outgoing_edges as a priority queue
hq.heapify(outgoing_edges)

In [ ]:
visited = set()  # Initialize a set to keep track of visited nodes
weights = []
for i, j in enumerate(prim_read_in.tolist()):

    visited.add(i)  # Add vertex to visited



for i, j in enumerate(prim_read_in.tolist()):
    visited.add(i)  # Add vertex to visited
    for edges in prim_read_in.tolist()[i]:  # Access adjacency matrix values
        hq.heappush(outgoing_edges, edges)  # Push all edge weights from one node to heap
        outgoing_edges.sort()  # Sort edges by weight
        weights.add(hq.heappop(outgoing_edges))  # Add smallest weight of neighboring edges


    hq.heappush(prim.mst, prim_read_in[i])  # Add
    weights.add(hq.heappop(outgoing_edges))  # Add smallest weight of neighboring edges

# Need a while group to add nodes to visited

outgoing_edges = []  # Initialize outgoing_edges as a priority queue
hq.heapify(outgoing_edges)

In [ ]:
# Add initial vertex
visited

In [ ]:
while v not in visited:
    # Pop lowest weight edge from priority queue
    hq.heappop(outgoing_edges)

    if next_v not in visited:
        hq.heappush(self.mst, next_v)  # Add edge to mst
        visited.add(next_v)

In [ ]:
total = 0                   # Total cost of edges in tree
explored = set()            # Set of vertices in tree
start = next(iter(graph))   # Arbitrary starting vertex
unexplored = [(0, start)]   # Unexplored edges ordered by cost
while unexplored:
    cost, winner = heappop(unexplored)
    if winner not in explored:
        explored.add(winner)
        total += cost
        for neighbour, cost in graph[winner]:
            if neighbour not in explored:
                heappush(unexplored, (cost, neighbour))
return total

In [ ]:
from mst import Graph

In [ ]:
prim_graph = Graph('./data/small.csv')


In [ ]:
print(prim_graph)

In [ ]:
len(prim_graph.adj_mat)

In [ ]:
prim_graph.adj_mat[0]

In [ ]:
visited = set()

for i, j in enumerate(prim_graph.adj_mat):
    visited.add(i)
    print(j)
    heap = [_ for _ in j]
print(heap)

In [ ]:
heap = [_ for _ in prim_graph.adj_mat[random_starting_index]]

In [ ]:
# Generate a random starting index in order to randomly choose a node from which to build the mst
random_starting_index = np.random.randint(0, len(prim_graph.adj_mat))

visited = set()  # Initialize set of visited nodes
visited.add(random_starting_index)  # Add starting nodes

# Starting node's smallest edge
next_edge = min([x for x in prim_graph.adj_mat[random_starting_index] if x > 0])

# Add edge to mst
#self.mst.append(next_edge)

# Next node in mst (finds index for which distance is least)
next_node, = np.where(prim_graph.adj_mat[random_starting_index] == next_edge)
print(next_node) '''NEED TO CONTROL FOR SAME VALUES'''
# Add node to visited set
visited.add(next_node)

In [ ]:
random_starting_index = np.random.randint(0, len(prim_graph.adj_mat))
heap = [_ for _ in prim_graph.adj_mat[random_starting_index]]
heap = hq.heappush(heap)
print(heap)

In [ ]:
heap = [i if i != 0 else np.inf for i in heap]  # Replace all zeros with infinity values
heap.sort()
print(heap)

In [ ]:
hq.heappop(heap)
print(heap)

In [ ]:
prim_graph.adj_mat[prim_graph.adj_mat == 0] = np.inf
print(prim_graph.adj_mat)

In [ ]:
heap = [_ for _ in prim_graph.adj_mat[random_starting_index]]
hq.heapify(heap)

In [ ]:
print(heap)

In [ ]:
hq.heappop(heap)
print(heap)

In [ ]:
prim_mst = []
visited = set()

random_starting_node = np.random.randint(0, len(prim_graph.adj_mat))
prim_graph.adj_mat[prim_graph.adj_mat == 0] = np.inf  # Replace all zeros with infinity
heap = [_ for _ in prim_graph.adj_mat[random_starting_node]]  # Return edges for random node
hq.heapify(heap)  # Heapify heap

visited.add(random_starting_node)  # Add first node to visited

curr_node = random_starting_node

while heap and len(visited) != len(prim_graph.adj_mat):
    shortest_edge = hq.heappop(heap)  # Pop shortest_edge
    curr_node = prim_graph.adj_mat[curr_node].tolist().index(shortest_edge)  # Assign index to next node
    if curr_node not in visited:  # Check if neighboring node is already in visited
        visited.add(curr_node)
        prim_mst.append(shortest_edge)  # Add edge to mst
        neighbor_edges = [_ for _ in prim_graph.adj_mat[curr_node]]
        hq.heappush(heap, neighbor_edges)

In [ ]:
prim_graph.adj_mat[0]

In [ ]:
val = 5.
index = prim_graph.adj_mat[0].tolist().index(val)
print(index)

In [ ]:
heap_practice = [0.0, 1.0, 0.0, 4.0]
hq.heapify(heap_practice)
print(heap_practice)

In [ ]:
heap_practice[heap_practice == 0] = np.inf

In [ ]:
print(heap_practice)

In [ ]:
heap_practice = [i if i != 0 else np.inf for i in heap_practice]

In [ ]:
print(heap_practice)

In [ ]:
heap_practice.sort()
hq.heappop(heap_practice)
print(heap_practice)

In [ ]:
prim_graph.adj_mat

In [ ]:
prim_graph_index_mat = np.ndenumerate(prim_graph.adj_mat)
for i, j in enumerate(prim_graph.adj_mat):

    print(i,j[0])

In [ ]:
random_starting_index = np.random.randint(0, len(prim_graph.adj_mat))
prim_graph.adj_mat[prim_graph.adj_mat == 0] = np.inf  # Replace all zeros with infinity
heap = [_ for _ in prim_graph.adj_mat[random_starting_index]]  # Return edges for random node

hq.heapify(heap)

In [ ]:
print(heap)

In [ ]:
shortest_edge = hq.heappop(heap)

In [ ]:
print(shortest_edge)

In [517]:
def check_mst(adj_mat: np.ndarray,
              mst: np.ndarray,
              expected_weight: int,
              allowed_error: float = 0.0001):
    """

    Helper function to check the correctness of the adjacency matrix encoding an MST.
    Note that because the MST of a graph is not guaranteed to be unique, we cannot
    simply check for equality against a known MST of a graph.

    Arguments:
        adj_mat: adjacency matrix of full graph
        mst: adjacency matrix of proposed minimum spanning tree
        expected_weight: weight of the minimum spanning tree of the full graph
        allowed_error: allowed difference between proposed MST weight and `expected_weight`

    TODO: Add additional assertions to ensure the correctness of your MST implementation. For
    example, how many edges should a minimum spanning tree have? Are minimum spanning trees
    always connected? What else can you think of?

    """

    def approx_equal(a, b):
        return abs(a - b) < allowed_error

    total = 0
    for i in range(mst.shape[0]):
        for j in range(i+1):
            total += mst[i, j]
    assert approx_equal(total, expected_weight), 'Proposed MST has incorrect expected weight'


def test_mst_small():
    """

    Unit test for the construction of a minimum spanning tree on a small graph.

    """
    file_path = './data/small.csv'
    g = Graph(file_path)
    g.construct_mst()
    check_mst(g.adj_mat, g.mst, 8)


def test_mst_single_cell_data():
    """

    Unit test for the construction of a minimum spanning tree using single cell
    data, taken from the Slingshot R package.

    https://bioconductor.org/packages/release/bioc/html/slingshot.html

    """
    file_path = '../data/slingshot_example.txt'
    coords = np.loadtxt(file_path) # load coordinates of single cells in low-dimensional subspace
    dist_mat = pairwise_distances(coords) # compute pairwise distances to form graph
    g = Graph(dist_mat)
    g.construct_mst()
    check_mst(g.adj_mat, g.mst, 57.263561605571695)

In [518]:
prim_graph = Graph('./data/small.csv')

In [520]:
prim_graph.adj_mat

array([[0., 5., 0., 5.],
       [5., 0., 1., 2.],
       [0., 1., 0., 4.],
       [5., 2., 4., 0.]])

In [522]:
from mst import Graph

In [523]:
prim_graph = Graph('./data/small.csv')


In [535]:
prim_graph.construct_mst()

In [536]:
prim_graph.mst

In [537]:
print(prim_graph.mst)

None


In [527]:
prim_graph.adj_mat.ndim

2

In [530]:
print(prim_graph.mst)

None


In [538]:
len(prim_graph.adj_mat)

4

In [539]:
prim_graph.construct_mst()

In [540]:
print(prim_graph.mst)

None


In [543]:
total = 0
mst = ([0, 5, 0, 0], [5, 0, 1, 2], [0, 1, 0, 0], [0, 2, 0, 0])
mst = np.array(mst)
for i in range(len(mst)):
   for j in range(i+1):
      total += mst[i, j]

In [544]:
print(total)

8


In [549]:

mst_zeros = np.zeros((4,4))
len(mst_zeros)

4

In [550]:
mst_zeros_two = np.zeros((len(mst_zeros), len(mst_zeros)))

In [551]:
print(mst_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
